Feature/footeк
chidorishar/filmoteka-team-project pull request #1
Opened 2022-10-06 12:13 UTC by Nadiia27j

2022-10-06 18:34 UTC, chidorishar commented
Сделать спрайт как мы обсудили на созвоне.

2022-10-06 18:46 UTC, chidorishar requested changes
Поправить замечания

2022-10-06 18:46 UTC, chidorishar commented on src/html/gallery.html
> +      <h3 class="film-card__title">FILM TITLE</h3>
Добавь свойство в стиль, которое делает все буквы названия фильма прописными

2022-10-06 18:46 UTC, chidorishar commented on src/html/gallery.html
> +    <div class="film-card is-hidden" >
У карточки должна быть фиксированная высота как по макету. При этом изображение должно будет подстроиться.

2022-10-06 18:46 UTC, chidorishar commented on src/html/gallery.html
> +      <h3 class="film-card__title">FILM TITLE</h3>
Поправь размер шрифтов названия фильма, жанра, года и оценки для разных устройств. Ты забыла размеры шрифтов менять для разных девайсов. Сверься с макетом.

2022-10-06 18:46 UTC, chidorishar commented on src/sass/layout/_gallery.scss
> +.film-card__box {
Стили для карточки в отдельный SCSS-файл вынеси.

2022-10-07 07:47 UTC, Nadiia27j commented on src/html/footer.html
> +      <div class="footer-section__text">©  2022 | All Rights Reserved |</div>
якщо зробити спанами тоді не виходить правильне позиціонування написів.

2022-10-07 15:22 UTC, chidorishar requested changes
Нужны правки.

2022-10-07 15:22 UTC, chidorishar commented on src/html/footer.html
> +        by<span class="footer-section__acсent">GoIT Students</span>
GoIT Students сделать ссылкой

2022-10-07 15:22 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +@keyframes pulse {
Анимации в отдельном файле должны лежать жеж, как было в прошлом проекте.
https://github.com/chidorishar/icecream-team-project/blob/500e765426209881be3675838417f579294cc003/src/sass/base/_animations.scss

2022-10-07 15:22 UTC, chidorishar commented on src/sass/layout/_footer.scss
>    font-style: normal;
Удали, это свойство наследуется глобально.

2022-10-07 15:22 UTC, chidorishar commented on src/html/footer.html
> +        by<span class="footer-section__acсent">GoIT Students</span>
Пробела не хватает
![изображение](https://user-images.githubusercontent.com/13747383/194589896-d45830dd-9109-4ea6-924b-53c40c78ddd3.png)

2022-10-08 13:12 UTC, chidorishar approved these changes
Двигаемся дальше

2022-10-08 13:19 UTC, chidorishar approved these changes
Заресолвено

2022-10-08 13:19 UTC, merged