team-modal
chidorishar/filmoteka-team-project pull request #10
Opened 2022-10-07 23:34 UTC by IrynaKniazieva

add modal window team

2022-10-08 11:14 UTC, chidorishar requested changes
Нужны небольшие визуальные правки модалки. Подробности - в слаке.

2022-10-09 18:27 UTC, chidorishar requested changes
Гуд. Чистенько-красиво. Правь и двигаемся дальше.

2022-10-09 18:27 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +// --STYLES FOR MOBILE-WINDOW TEAM --
Вынеси стили в отдельный scss файл

2022-10-09 18:27 UTC, chidorishar commented on src/html/footer.html
> +  <div class="container">
В отдельный html-файл разметку

2022-10-09 18:27 UTC, chidorishar commented on src/html/footer.html
> +        <button class="modal-wrapper__button" data-modal-close>
Ариа-атрибут добавь по примеру. Только текст поменяй на такой, который описывает функционал кнопки
https://github.com/chidorishar/filmoteka-team-project/blob/e180718cf002fc64bc9fdd2c414fd8f2356f89b1/src/html/modal-window.html#L8

2022-10-09 18:27 UTC, chidorishar commented on src/html/footer.html
> +                <p class="team-info__name">OLEG</p>
Для имён участников сделай не p а h3

2022-10-09 18:27 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +  background-color: white;
Цвет из палитры возьми. Белый это #fff в хекс-записи.

2022-10-09 18:27 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +  background-color: white;
Тоже самое для других используемых цветов сделай.

2022-10-09 18:27 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +@media screen and (max-width: 767px) {
Все медиа-правила для адаптивной вёрстки на миксины перепиши 
https://trello.com/c/rVoaQ0k1/88-%D0%BA%D0%B0%D0%BA-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BC%D0%B8%D0%BA%D1%81%D0%B8%D0%BD%D1%8B-%D0%B4%D0%BB%D1%8F-%D0%B0%D0%B4%D0%B0%D0%BF%D1%82%D0%B8%D0%B2%D0%BD%D0%BE%D0%B9-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B8-%D0%BE%D1%81%D0%BD%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%B9-%D0%BD%D0%B0-%D0%B1%D1%80%D0%B5%D0%BA%D0%BF%D0%BE%D0%B8%D0%BD%D1%82%D0%B0%D1%85

2022-10-09 22:01 UTC, IrynaKniazieva commented on src/sass/layout/_footer.scss
> +  background-color: white;
+

2022-10-09 22:01 UTC, IrynaKniazieva commented on src/html/footer.html
> +                <p class="team-info__name">OLEG</p>
+

2022-10-09 22:03 UTC, IrynaKniazieva commented on src/html/footer.html
> +        <button class="modal-wrapper__button" data-modal-close>
добавлено

2022-10-09 22:04 UTC, IrynaKniazieva commented on src/html/footer.html
> +  <div class="container">
+

2022-10-09 22:04 UTC, IrynaKniazieva commented on src/sass/layout/_footer.scss
> +// --STYLES FOR MOBILE-WINDOW TEAM --
+

2022-10-09 22:04 UTC, IrynaKniazieva commented on src/sass/layout/_footer.scss
> +@media screen and (max-width: 767px) {
+

2022-10-10 09:25 UTC, chidorishar approved these changes
Двигаемся дальше...

2022-10-10 09:26 UTC, merged