Feature FT-06
chidorishar/filmoteka-team-project pull request #2
Opened 2022-10-06 15:21 UTC by myroslavsuprun

2022-10-06 19:09 UTC, chidorishar requested changes
Уффф! Ну ты и начудил. 😡

2022-10-06 19:09 UTC, chidorishar commented on src/sass/index.css
> +.modal {
Что тут за модалка?

2022-10-06 19:09 UTC, chidorishar commented on src/sass/index.css
> +html {
https://github.com/chidorishar/filmoteka-team-project/blob/4d70ccf92a398b38a3efb76a80f8a8c0f1c0646c/src/sass/base/_globals.scss#L1

2022-10-07 10:20 UTC, Geljinskiy approved these changes

2022-10-07 10:22 UTC, Geljinskiy approved these changes

2022-10-07 10:58 UTC, closed without merging