add loader
chidorishar/filmoteka-team-project pull request #3
Opened 2022-10-06 17:17 UTC by Nadiia27j

2022-10-06 17:42 UTC, chidorishar requested changes
Учесть комментарии.

2022-10-06 17:42 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +@keyframes loader {
Анимации - в отдельный файл по примеру
анимация: https://github.com/chidorishar/icecream-team-project/blob/500e765426209881be3675838417f579294cc003/src/sass/base/_animations.scss
её подключение: https://github.com/chidorishar/icecream-team-project/blob/500e765426209881be3675838417f579294cc003/src/sass/base/_all-partials.scss#L1

2022-10-06 17:42 UTC, chidorishar commented on src/sass/layout/_footer.scss
> +
Стили лоадера - в отдельный файл,

2022-10-06 17:42 UTC, chidorishar commented on src/html/footer.html
> +
Разметку лоадера тоже в отдельный файл.

2022-10-06 18:54 UTC, chidorishar requested changes
Рассмотреть замечания 😊

2022-10-06 18:54 UTC, chidorishar commented on src/sass/layout/_loader.scss
> +    background: #fff;
Цвет из палитры возьми

2022-10-06 18:54 UTC, chidorishar commented on src/sass/layout/_loader.scss
> +    opacity: 0;
pointer events none ещё не забудь

2022-10-06 18:54 UTC, chidorishar commented on src/sass/layout/_loader.scss
> +    border-radius: 50%;
Замени на плейсхолдер: https://github.com/chidorishar/filmoteka-team-project/blob/4d70ccf92a398b38a3efb76a80f8a8c0f1c0646c/src/sass/utils/_placeholders.scss#L12

2022-10-06 19:14 UTC, Nadiia27j commented on src/sass/layout/_loader.scss
> +    border-radius: 50%;
нерозумію як виправити

2022-10-07 15:01 UTC, chidorishar requested changes
Маленькие замечания.

2022-10-07 15:01 UTC, chidorishar commented on src/index.js
> +let maskEl = document.querySelector('.mask');
Окей, всё норм с классами. JS-код целиком убирай.

2022-10-07 15:01 UTC, chidorishar commented on src/sass/components/_loader.scss
> +  border: 10px solid rgba(62, 190, 141, 0.6);
Цвет в палитру вынеси

2022-10-07 15:01 UTC, chidorishar commented on src/sass/components/_loader.scss
> +  border-left-color: rgba(62, 190, 141);
Цвет в палитру вынеси

2022-10-08 08:22 UTC, Nadiia27j commented on src/index.js
> +let maskEl = document.querySelector('.mask');
а для чого js видаляти ,хіба він не потрібен?

2022-10-08 15:57 UTC, chidorishar commented on src/index.js
> +let maskEl = document.querySelector('.mask');
Не, не нужон

2022-10-08 17:40 UTC, Nadiia27j commented on src/index.js
> +let maskEl = document.querySelector('.mask');
ок

2022-10-09 21:40 UTC, chidorishar approved these changes
Некуросиво, ну да ладно...

2022-10-09 21:43 UTC, merged