add markUp header myLibrary
chidorishar/filmoteka-team-project pull request #4
Opened 2022-10-06 20:57 UTC by korzhenkovitalii

2022-10-07 21:18 UTC, myroslavsuprun requested changes
- Еще добавить фон затемнения для фона. `background: rgba(0, 0, 0, 0.56);`

- Начиная с tablet отступы по бокам (padding) не 15 пикселей, а 32 пикселя. Это уже в main исправлено, можно просто запулить.

Так, все супер. Приятно было читать код. Картинки под разные версии отлично подгружаются с разным dpr

2022-10-07 21:18 UTC, myroslavsuprun commented on src/sass/layout/_header-library.scss
> +  color: red;
getColorFromPalette

2022-10-07 21:18 UTC, myroslavsuprun commented on src/sass/components/_button.scss
> +  color: #ffffff;
getColorFromPalette

2022-10-07 21:18 UTC, myroslavsuprun commented on src/sass/components/_button.scss
> +  font-family: 'Roboto';
font-family и font-style наследуются от body, можно убрать

2022-10-07 21:18 UTC, myroslavsuprun commented on src/sass/components/_button.scss
> +  background: #ff6b01;
getColorFromPalette

2022-10-08 11:46 UTC, chidorishar requested changes
Нужны правки. Часть замечаний в слаке.

2022-10-08 11:46 UTC, chidorishar commented on src/localStorageUtil.js
> +class LocalStorageUtil {
Класс для взаимодействия с локалСторейджем убери из этой ветки.

2022-10-08 11:46 UTC, chidorishar commented on src/index.html
> +    <include src="./html/header-library.html"></include>
При мёрдже нужно будет убрать отсюда

2022-10-08 11:46 UTC, chidorishar commented on src/html/header-library.html
> +    <div class="header__buttons">
![изображение](https://user-images.githubusercontent.com/13747383/194705701-c6b1b899-ad82-4506-81dc-ac6c8c5da26b.png)

2022-10-09 21:19 UTC, closed without merging